name: Release

on:
  pull_request:
    branches:
      - stable
    types:
      - closed

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  GH_USER_EMAIL: ${{ secrets.DETRA_BOT_EMAIL }}
  GH_TOKEN: ${{ secrets.DETRA_GH_PAT }}
  NPM_TOKEN: ${{ secrets.DETRA_NPM_PAT }}

jobs:
  release:
    if: ${{ github.event.pull_request.merged == true || !contains(github.event.pull_request.body, '[skip-ci]') }}

    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v3

      - name: ğŸ“¦ Setup PNPm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: ğŸŸ¢ Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: ğŸ§© Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: ğŸ—ï¸ Configure .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF

      - name: ğŸ—ï¸ Configure Git User
        run: |
          git config --global user.name "detra-bot"
          git config --global user.email "$GH_USER_EMAIL"

      - name: ğŸ“£ Create Release PR or Publish to NPM
        id: changesets
        uses: changesets/action@v1
        env:
          NPM_TOKEN: ${{ env.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ env.GH_TOKEN }}
        with:
          setupGitUser: false
          publish: pnpm run release
          title: 'chore: bump the package version'
          commit: 'chore: bump the package version'
